# -*- coding: utf-8 -*-
"""Mental Health in Tech Survey.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rew1mreblPSnPW1q4w6ekV-HNmPyaTB1

# **Project Name**    - Mental Health in Tech Survey EDA
"""

##### **Project Type**    - EDA
##### **Contribution**    - Individual

"""# **Project Summary -**

This project performs an in-depth Exploratory Data Analysis (EDA) on the 2014 Open Sourcing Mental Illness (OSMI) Mental Health in Tech Survey. The survey was designed to measure attitudes towards mental health and the frequency of mental health disorders in the technology workplace.

The dataset contains 1,259 responses collected from tech professionals across multiple countries. It covers a wide range of information including demographics (Age, Gender, Country, State), employment details (self-employed status, company size, remote work, whether the employer is a tech company), mental health history and treatment-seeking behaviour, workplace support systems (benefits, care options, wellness programs, anonymity protection, ease of taking leave), and attitudes towards discussing mental health versus physical health with employers, coworkers, and supervisors.

The primary goals of this EDA are:
1. To understand how the frequency of mental health issues and attitudes towards mental health vary by geographic location, company size, gender, and other factors.
2. To identify the strongest predictors of mental health treatment-seeking behaviour and negative workplace attitudes.
3. To uncover gaps in current employer support systems (awareness of benefits, anonymity, leave policies, etc.).
4. To provide actionable, data-driven recommendations that tech companies can use to reduce stigma, increase help-seeking, and improve employee well-being.

The analysis follows a structured approach: data understanding, thorough data cleaning & wrangling (especially Age and Gender), univariate, bivariate and multivariate visualizations (minimum 20 charts), correlation analysis, and clear business recommendations.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

Mental health issues are highly prevalent in the technology industry, yet stigma, lack of awareness about available support, and fear of negative career consequences often prevent employees from seeking help.

Organizations currently lack clear, data-backed answers to important questions such as:
- How does the frequency of mental health illness and attitudes towards mental health vary by geographic location?
- What are the strongest predictors of mental health treatment-seeking behaviour or certain attitudes in the workplace?
- Where are the biggest gaps in employer-provided support (benefits awareness, anonymity, leave policies, manager openness, etc.)?

Without these insights, companies risk designing ineffective wellness programs, wasting resources on benefits that employees do not know about, and failing to create a psychologically safe culture. This EDA aims to fill that knowledge gap using real survey data from 2014.

#### **Define Your Business Objective?**

Help technology organizations understand the real prevalence of mental health concerns among their employees, identify the most critical gaps in current support systems, and prioritize high-impact interventions that reduce stigma and increase help-seeking behaviour.

The ultimate business goal is to improve employee well-being, reduce productivity loss caused by untreated mental health issues, lower attrition, and build a more supportive and sustainable workplace culture around mental health.

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Set visual style
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

print("Libraries imported successfully!")

"""### Dataset Loading"""

# Load Dataset
df = pd.read_csv('survey.csv')   # Change path if your file is in a different location
print("Dataset loaded successfully!")

"""### Dataset First View"""

# Dataset First Look
df.head()

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
print(f"Number of Rows    : {df.shape[0]}")
print(f"Number of Columns : {df.shape[1]}")

"""### Dataset Information"""

# Dataset Info
df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
duplicate_count = df.duplicated().sum()
print(f"Total Duplicate Rows: {duplicate_count}")

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Percentage (%)': missing_pct.round(2)
})

# Show only columns that have missing values
missing_df = missing_df[missing_df['Missing Count'] > 0].sort_values('Missing Count', ascending=False)
print(missing_df)

# Visualizing the missing values
plt.figure(figsize=(14, 6))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis', yticklabels=False)
plt.title('Missing Values Heatmap', fontsize=15, pad=15)
plt.tight_layout()
plt.show()

"""### What did you know about your dataset?

After the initial exploration, the following key observations can be made:

- The dataset contains **1,259 rows** and **27 columns**.
- It is the official 2014 OSMI Mental Health in Tech Survey.
- Almost all columns are categorical (object type). Only the `Age` column is numeric, but it contains extreme and unrealistic values (negative ages and ages in the millions/billions).
- There are **no exact duplicate rows**.
- Significant missing values exist in the following columns:
  - `comments` → approximately 87% missing (expected for optional free-text field)
  - `state` → missing mainly for respondents outside the United States
  - `work_interfere` → 264 missing values
  - `self_employed` → 18 missing values
- The `Gender` column has a large number of inconsistent free-text entries (e.g., “Male”, “male”, “M”, “maile”, “Male-ish”, “Cis Male”, “Trans-female”, etc.) and will require careful cleaning.
- The dataset is rich in workplace mental-health related questions and is well-suited for both univariate and bivariate analysis of attitudes, treatment-seeking behaviour, and support systems.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
print("List of all columns in the dataset:\n")
print(df.columns.tolist())

# Dataset Describe
df.describe(include='all')

"""### Variables Description

| Variable | Description |
|----------|-------------|
| **Timestamp** | Date and time when the survey response was submitted |
| **Age** | Age of the respondent (numeric) |
| **Gender** | Gender identity of the respondent (free-text, needs cleaning) |
| **Country** | Country where the respondent lives |
| **state** | US state or territory (only for respondents in the United States) |
| **self_employed** | Whether the respondent is self-employed (Yes / No) |
| **family_history** | Whether the respondent has a family history of mental illness (Yes / No) |
| **treatment** | Whether the respondent has sought treatment for a mental health condition (Yes / No) – **Important target variable** |
| **work_interfere** | If the respondent has a mental health condition, how often it interferes with work (Never / Rarely / Sometimes / Often) |
| **no_employees** | Size of the company / organization (1-5, 6-25, 26-100, 100-500, 500-1000, More than 1000) |
| **remote_work** | Whether the respondent works remotely at least 50% of the time (Yes / No) |
| **tech_company** | Whether the employer is primarily a tech company / organization (Yes / No) |
| **benefits** | Does the employer provide mental health benefits? (Yes / No / Don't know) |
| **care_options** | Does the respondent know the options for mental health care provided by the employer? (Yes / No / Not sure) |
| **wellness_program** | Has the employer ever discussed mental health as part of an employee wellness program? (Yes / No / Don't know) |
| **seek_help** | Does the employer provide resources to learn more about mental health issues and how to seek help? (Yes / No / Don't know) |
| **anonymity** | Is anonymity protected if the employee uses mental health or substance abuse treatment resources? (Yes / No / Don't know) |
| **leave** | How easy is it to take medical leave for a mental health condition? (Very easy / Somewhat easy / Don't know / Somewhat difficult / Very difficult) |
| **mental_health_consequence** | Do you think discussing a mental health issue with your employer would have negative consequences? (Yes / No / Maybe) |
| **phys_health_consequence** | Do you think discussing a physical health issue with your employer would have negative consequences? (Yes / No / Maybe) |
| **coworkers** | Would you be willing to discuss a mental health issue with your coworkers? (Yes / No / Some of them) |
| **supervisor** | Would you be willing to discuss a mental health issue with your direct supervisor(s)? (Yes / No / Some of them) |
| **mental_health_interview** | Would you bring up a mental health issue with a potential employer in an interview? (Yes / No / Maybe) |
| **phys_health_interview** | Would you bring up a physical health issue with a potential employer in an interview? (Yes / No / Maybe) |
| **mental_vs_physical** | Do you feel that your employer takes mental health as seriously as physical health? (Yes / No / Don't know) |
| **obs_consequence** | Have you heard of or observed negative consequences for coworkers with mental health conditions in your workplace? (Yes / No) |
| **comments** | Any additional notes or comments (free-text, mostly empty) |

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable
print("Unique values and count for each column:\n")
print("="*70)

for col in df.columns:
    nunique = df[col].nunique()
    print(f"\n▶ {col}")
    print(f"  Number of unique values: {nunique}")

    # Show the actual unique values only if they are not too many
    if nunique <= 15:
        print(f"  Values → {df[col].unique().tolist()}")
    else:
        print(f"  (Too many unique values to display)")

"""**Key Observations from Understanding Variables:**

- Most variables are categorical. Only `Age` is continuous (and it needs cleaning because of outliers).
- `treatment` is a clear binary target variable that we will use heavily in bivariate analysis.
- Several important columns have three categories including “Don’t know” or “Not sure” (`benefits`, `care_options`, `anonymity`, `leave`, `mental_vs_physical`, etc.). These “Don’t know” responses are very insightful — they indicate communication gaps.
- `Gender` has a high number of unique free-text values and must be cleaned in the next stage.
- `Country` is dominated by United States, United Kingdom, Canada, etc. We may later group smaller countries for cleaner analysis.
- `work_interfere` and `self_employed` still have missing values that we will handle during Data Wrangling.

## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.

# 1. Create a working copy
df_clean = df.copy()
print("Original shape:", df_clean.shape)

# -------------------------------------------------
# 2. Clean Age column (remove unrealistic values)
# Keep only ages between 18 and 75 (realistic working age range)
# -------------------------------------------------
print("\nAge statistics BEFORE cleaning:")
print(df_clean['Age'].describe())

df_clean = df_clean[(df_clean['Age'] >= 18) & (df_clean['Age'] <= 75)]

print("\nAge statistics AFTER cleaning:")
print(df_clean['Age'].describe())
print(f"Rows remaining after Age cleaning: {len(df_clean)}")

# -------------------------------------------------
# 3. Clean Gender column
# Map all free-text / misspelled entries into 3 clean categories:
# Male / Female / Other
# -------------------------------------------------
def clean_gender(gender):
    if pd.isna(gender):
        return 'Other'

    g = str(gender).strip().lower()

    # Male related terms
    male_keywords = ['male', 'm', 'male-ish', 'maile', 'cis male', 'mal',
                     'male (cis)', 'make', 'man', 'msle', 'mail', 'malr',
                     'cis man', 'male ', 'guy']

    # Female related terms
    female_keywords = ['female', 'f', 'woman', 'female ', 'cis female',
                       'femake', 'female (cis)', 'femail', 'trans-female',
                       'trans woman', 'female (trans)', 'woman']

    if g in male_keywords or ('male' in g and 'female' not in g and 'trans' not in g):
        return 'Male'
    elif g in female_keywords or ('female' in g) or g == 'f':
        return 'Female'
    else:
        return 'Other'

df_clean['Gender_clean'] = df_clean['Gender'].apply(clean_gender)

print("\nGender distribution AFTER cleaning:")
print(df_clean['Gender_clean'].value_counts())

# -------------------------------------------------
# 4. Handle missing values in self_employed
# -------------------------------------------------
# Most respondents are not self-employed. Filling with mode ('No')
df_clean['self_employed'] = df_clean['self_employed'].fillna('No')

# -------------------------------------------------
# 5. Handle missing values in work_interfere
# -------------------------------------------------
# Missing usually means the person did not report a mental health condition
# We create a clear category for analysis
df_clean['work_interfere'] = df_clean['work_interfere'].fillna('Not applicable')

# -------------------------------------------------
# 6. Create Age Groups (useful for visualization)
# -------------------------------------------------
bins = [17, 25, 35, 45, 55, 75]
labels = ['18-25', '26-35', '36-45', '46-55', '56+']
df_clean['Age_group'] = pd.cut(df_clean['Age'], bins=bins, labels=labels)

print("\nAge Group distribution:")
print(df_clean['Age_group'].value_counts().sort_index())

# -------------------------------------------------
# 7. Group less frequent countries into 'Other'
# Keep top 8 countries for cleaner geographic analysis
# -------------------------------------------------
top_countries = df_clean['Country'].value_counts().nlargest(8).index.tolist()
df_clean['Country_grouped'] = df_clean['Country'].apply(
    lambda x: x if x in top_countries else 'Other'
)

print("\nCountry (grouped) distribution:")
print(df_clean['Country_grouped'].value_counts())

# -------------------------------------------------
# 8. Drop columns that are not useful for quantitative EDA
# -------------------------------------------------
# - comments : mostly empty free text
# - Timestamp : not needed for current analysis
# - Original Gender : we now have Gender_clean
df_clean = df_clean.drop(columns=['comments', 'Timestamp', 'Gender'], errors='ignore')

# -------------------------------------------------
# Final check
# -------------------------------------------------
print("\n" + "="*60)
print("DATA WRANGLING COMPLETED SUCCESSFULLY")
print("="*60)
print(f"Final shape of cleaned dataset: {df_clean.shape}")
print("\nRemaining missing values:")
print(df_clean.isnull().sum()[df_clean.isnull().sum() > 0])

"""### What all manipulations have you done and insights you found?

**Manipulations Performed:**

1. **Age Cleaning**  
   Removed unrealistic age values (negative numbers and extremely large numbers). Kept only respondents aged between 18 and 75 years (realistic working age). This reduced the dataset slightly but made Age analysis reliable.

2. **Gender Standardization**  
   The original Gender column contained many free-text and misspelled entries (e.g., “Male”, “male”, “M”, “maile”, “Male-ish”, “Cis Male”, “Trans-female”, “femail”, etc.).  
   All these were mapped into three clean categories: **Male**, **Female**, and **Other**.

3. **Missing Value Treatment**  
   - `self_employed`: Filled missing values with ‘No’ (the clear majority class).  
   - `work_interfere`: Filled missing values with ‘Not applicable’ so that the column can be used in visualizations without dropping rows.

4. **Feature Engineering**  
   - Created `Age_group` (18-25, 26-35, 36-45, 46-55, 56+) for easier categorical analysis.  
   - Created `Country_grouped` by keeping the top 8 countries and grouping the rest as ‘Other’. This avoids cluttered charts caused by many countries with very few responses.

5. **Column Dropping**  
   Removed `comments` (mostly empty), `Timestamp` (not needed for analysis), and the original messy `Gender` column (replaced by `Gender_clean`).

**Insights Found During Wrangling:**

- After cleaning, the dataset is now clean and analysis-ready.
- The workforce is relatively young (majority between 26–35 years).
- Strong gender imbalance exists (typical of the tech industry in 2014) — Male respondents form the large majority.
- Family history and treatment columns are complete (no missing values) — these will be important for bivariate analysis.
- Many “Don’t know” answers exist in support-related questions (benefits, anonymity, leave, etc.). These are not missing data; they are meaningful signals of poor communication by employers.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1: Treatment Seeking Distribution (Univariate)
"""

# Chart - 1 visualization code
plt.figure(figsize=(8, 5))
ax = sns.countplot(data=df_clean, x='treatment', palette='Set2', order=['Yes', 'No'])
plt.title('Have Respondents Sought Treatment for a Mental Health Condition?', fontsize=14, pad=12)
plt.xlabel('Sought Treatment')
plt.ylabel('Number of Respondents')

# Add count labels on bars
for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom', fontsize=11)

plt.tight_layout()
plt.show()

# Percentage view
print("\nPercentage Distribution:")
print(df_clean['treatment'].value_counts(normalize=True).round(3) * 100)

"""##### 1. Why did you pick the specific chart?

A simple count plot is the most effective way to show the distribution of a binary categorical variable. It immediately tells us how balanced the key outcome variable (`treatment`) is.

##### 2. What is/are the insight(s) found from the chart?

Almost half of the respondents (approximately 50.5%) have sought treatment for a mental health condition, while the other half have not. This near 50-50 split shows that mental health concerns are extremely common in the tech workforce.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. Knowing that roughly one in two employees has sought (or needed) treatment creates a strong business case for investing in mental health benefits, Employee Assistance Programs (EAPs), and stigma-reduction initiatives. Ignoring this reality can lead to higher absenteeism, lower productivity, and increased turnover — all of which negatively affect growth.

#### Chart - 2: Age Distribution (Univariate)
"""

# Chart - 2 visualization code
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Histogram + KDE
sns.histplot(df_clean['Age'], bins=20, kde=True, ax=axes[0], color='steelblue')
axes[0].set_title('Age Distribution (Histogram + KDE)', fontsize=13)
axes[0].set_xlabel('Age')
axes[0].set_ylabel('Count')

# Boxplot
sns.boxplot(y=df_clean['Age'], ax=axes[1], color='lightblue')
axes[1].set_title('Age Boxplot', fontsize=13)
axes[1].set_ylabel('Age')

plt.tight_layout()
plt.show()

print(df_clean['Age'].describe())

"""##### 1. Why did you pick the specific chart?

A histogram with KDE shows the overall shape and concentration of the Age variable, while the boxplot clearly displays the median, quartiles, and any remaining outliers.

##### 2. What is/are the insight(s) found from the chart?

The majority of respondents are between 25 and 40 years old (median age is around 31). The tech workforce in this survey is relatively young, which is typical for the industry.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. Mental health programs can be tailored to a predominantly young / early-to-mid career demographic (career pressure, work-life balance, financial stress, etc.). Designing programs only for older employees would miss the largest segment of the workforce.

#### Chart - 3: Gender Distribution (Univariate)
"""

# Chart - 3 visualization code
plt.figure(figsize=(8, 5))
ax = sns.countplot(data=df_clean, x='Gender_clean',
                   order=['Male', 'Female', 'Other'], palette='pastel')
plt.title('Gender Distribution of Respondents', fontsize=14, pad=12)
plt.xlabel('Gender')
plt.ylabel('Number of Respondents')

for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom', fontsize=11)

plt.tight_layout()
plt.show()

print("\nPercentage Distribution:")
print(df_clean['Gender_clean'].value_counts(normalize=True).round(3) * 100)

"""##### 1. Why did you pick the specific chart?

A count plot clearly shows the gender composition of the survey respondents and highlights the imbalance typical of the tech industry.

##### 2. What is/are the insight(s) found from the chart?

Males form the large majority (approximately 79%), Females around 20%, and Other around 1%. This reflects the gender distribution commonly seen in tech surveys from that period.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Positive impact: Programs should still be designed to be inclusive. Because women and non-binary individuals are under-represented in the sample, their experiences may be under-sampled. Companies should complement survey data with targeted listening sessions for these groups.

#### Chart - 4: Family History vs Treatment (Bivariate)
"""

# Chart - 4 visualization code
plt.figure(figsize=(9, 5))
ax = sns.countplot(data=df_clean, x='family_history', hue='treatment',
                   palette='Set1', order=['Yes', 'No'])
plt.title('Family History of Mental Illness vs Seeking Treatment', fontsize=14, pad=12)
plt.xlabel('Family History of Mental Illness')
plt.ylabel('Number of Respondents')
plt.legend(title='Sought Treatment')

plt.tight_layout()
plt.show()

# Crosstab with percentages
print("\nPercentage who sought treatment by Family History:")
ct = pd.crosstab(df_clean['family_history'], df_clean['treatment'], normalize='index') * 100
print(ct.round(1))

"""##### 1. Why did you pick the specific chart?

A grouped bar chart is ideal for comparing a binary outcome (`treatment`) across the categories of another categorical variable (`family_history`).

##### 2. What is/are the insight(s) found from the chart?

Respondents who have a family history of mental illness are significantly more likely to have sought treatment (around 70%+) compared to those without a family history (around 35–40%). Family history is one of the strongest predictors of treatment-seeking behaviour.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. Employers can use this insight to design targeted awareness campaigns and normalize help-seeking, especially for employees who recognize patterns in their family. Ignoring this high-need group can leave a large portion of employees without timely support.

#### Chart - 5: Work Interference Levels (Univariate)
"""

# Chart - 5 visualization code
order = ['Never', 'Rarely', 'Sometimes', 'Often', 'Not applicable']
plt.figure(figsize=(10, 5))
ax = sns.countplot(data=df_clean, x='work_interfere', order=order, palette='coolwarm')
plt.title('How Often Does Mental Health Interfere with Work?', fontsize=14, pad=12)
plt.xlabel('Work Interference Level')
plt.ylabel('Number of Respondents')
plt.xticks(rotation=15)

for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom', fontsize=10)

plt.tight_layout()
plt.show()

"""##### 1. Why did you pick the specific chart?

An ordered count plot is perfect for showing the frequency of different levels of work interference caused by mental health conditions.

##### 2. What is/are the insight(s) found from the chart?

A large number of respondents experience interference “Sometimes” or more frequently. Many also fall into the “Not applicable” category (no reported condition). Among those who do have a condition, work interference is quite common.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. Frequent work interference signals real productivity loss. Providing flexible leave, reasonable accommodations, and early support can reduce the “Often” and “Sometimes” categories, protecting both employee health and company performance.

#### Chart - 6: Company Size Distribution (Univariate)
"""

# Chart - 6 visualization code
size_order = ['1-5', '6-25', '26-100', '100-500', '500-1000', 'More than 1000']

plt.figure(figsize=(10, 5))
ax = sns.countplot(data=df_clean, x='no_employees', order=size_order, palette='viridis')
plt.title('Distribution of Company Size', fontsize=14, pad=12)
plt.xlabel('Number of Employees in the Company')
plt.ylabel('Number of Respondents')
plt.xticks(rotation=20)

for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom', fontsize=10)

plt.tight_layout()
plt.show()

"""##### 1. Why did you pick the specific chart?

An ordered bar chart clearly shows how many respondents come from different company size categories, which is important for understanding whether support systems differ by organization scale.

##### 2. What is/are the insight(s) found from the chart?

Respondents come from a good mix of company sizes. There is strong representation from both small companies (6-25 and 26-100 employees) and large organizations (More than 1000 employees). This allows us to later compare mental health support across different organization scales.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. Different sized companies have different resource constraints. Insights can be segmented so that recommendations for startups remain realistic, while large enterprises can be pushed for more comprehensive programs. A one-size-fits-all approach would be less effective.

#### Chart - 7: Does Employer Provide Mental Health Benefits? (Univariate)
"""

# Chart - 7 visualization code
plt.figure(figsize=(8, 5))
ax = sns.countplot(data=df_clean, x='benefits',
                   order=['Yes', 'No', "Don't know"], palette='Set2')
plt.title('Does Your Employer Provide Mental Health Benefits?', fontsize=14, pad=12)
plt.xlabel('Mental Health Benefits Provided')
plt.ylabel('Number of Respondents')

for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom', fontsize=11)

plt.tight_layout()
plt.show()

print("\nPercentage Distribution:")
print(df_clean['benefits'].value_counts(normalize=True).round(3) * 100)

"""##### 1. Why did you pick the specific chart?

A simple count plot is the best way to highlight the awareness (and lack of awareness) of employer-provided mental health benefits.

##### 2. What is/are the insight(s) found from the chart?

A large share of employees either do not have mental health benefits or (more importantly) do not know whether such benefits exist. The high percentage of “Don’t know” responses is a clear signal of poor communication by employers.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. Simply improving communication about existing benefits (through onboarding, intranet, manager talking points, regular reminders) can significantly increase utilization at very low cost. High “Don’t know” rates mean companies are paying for benefits that many employees never use — a clear inefficiency.

#### Chart - 8: Treatment Seeking by Gender (Bivariate)
"""

# Chart - 8 visualization code
plt.figure(figsize=(9, 5))
ax = sns.countplot(data=df_clean, x='Gender_clean', hue='treatment',
                   order=['Male', 'Female', 'Other'], palette='Set1')
plt.title('Treatment Seeking Behaviour by Gender', fontsize=14, pad=12)
plt.xlabel('Gender')
plt.ylabel('Number of Respondents')
plt.legend(title='Sought Treatment')

plt.tight_layout()
plt.show()

print("\nPercentage who sought treatment by Gender:")
ct = pd.crosstab(df_clean['Gender_clean'], df_clean['treatment'], normalize='index') * 100
print(ct.round(1))

"""##### 1. Why did you pick the specific chart?

A grouped bar chart allows direct comparison of treatment rates across different gender categories.

##### 2. What is/are the insight(s) found from the chart?

Female respondents show a noticeably higher rate of having sought treatment compared to Male respondents. This may reflect differences in help-seeking behaviour, prevalence, or willingness to disclose mental health issues.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. Gender-sensitive approaches are needed. In particular, organizations should work on reducing stigma among male employees so that they feel safer seeking help. Leaving this gap unaddressed can result in higher rates of untreated conditions among a large portion of the workforce.

#### Chart - 9: Remote Work vs Treatment Seeking (Bivariate)
"""

# Chart - 9 visualization code
plt.figure(figsize=(8, 5))
ax = sns.countplot(data=df_clean, x='remote_work', hue='treatment', palette='coolwarm')
plt.title('Remote Work vs Seeking Treatment', fontsize=14, pad=12)
plt.xlabel('Works Remotely at least 50% of the time')
plt.ylabel('Number of Respondents')
plt.legend(title='Sought Treatment')

plt.tight_layout()
plt.show()

print("\nPercentage who sought treatment by Remote Work status:")
ct = pd.crosstab(df_clean['remote_work'], df_clean['treatment'], normalize='index') * 100
print(ct.round(1))

"""##### 1. Why did you pick the specific chart?

A grouped count plot is effective for comparing treatment rates between employees who work remotely and those who do not.

##### 2. What is/are the insight(s) found from the chart?

Treatment rates are quite similar between remote and non-remote workers. Remote work itself does not appear to be a major differentiator for treatment-seeking behaviour in this 2014 sample.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The insight is neutral-to-positive. Mental health support should be equally available and visible to both remote and in-office employees. Assuming that remote workers need less support would be a mistake and could lead to under-serving a growing part of the workforce.

#### Chart - 10: Perception of Negative Consequences for Discussing Mental Health (Univariate)
"""

# Chart - 10 visualization code
plt.figure(figsize=(8, 5))
ax = sns.countplot(data=df_clean, x='mental_health_consequence',
                   order=['No', 'Maybe', 'Yes'], palette='RdYlGn_r')
plt.title('Do You Think Discussing Mental Health with Employer\nWould Have Negative Consequences?', fontsize=13, pad=12)
plt.xlabel('Negative Consequences Expected')
plt.ylabel('Number of Respondents')

for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom', fontsize=11)

plt.tight_layout()
plt.show()

print("\nPercentage Distribution:")
print(df_clean['mental_health_consequence'].value_counts(normalize=True).round(3) * 100)

"""##### 1. Why did you pick the specific chart?

A count plot of this ordinal perception variable clearly reveals how much fear still exists around disclosing mental health issues at work.

##### 2. What is/are the insight(s) found from the chart?

A substantial portion of employees answered “Maybe” or “Yes”. This indicates that a significant number of people still fear that discussing mental health with their employer could harm their career.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. High fear of negative consequences is a direct barrier to early intervention. Leadership messaging, manager training, and visible support from senior leaders can reduce this fear. If left unaddressed, employees will continue to hide issues until they become more severe, leading to higher long-term costs and turnover.

#### Chart - 11: Willingness to Discuss Mental Health with Supervisor (Univariate)
"""

# Chart - 11 visualization code
plt.figure(figsize=(8, 5))
ax = sns.countplot(data=df_clean, x='supervisor',
                   order=['Yes', 'Some of them', 'No'], palette='Blues')
plt.title('Would You Be Willing to Discuss a Mental Health Issue\nwith Your Direct Supervisor(s)?', fontsize=13, pad=12)
plt.xlabel('Willingness to Discuss with Supervisor')
plt.ylabel('Number of Respondents')

for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom', fontsize=11)

plt.tight_layout()
plt.show()

print("\nPercentage Distribution:")
print(df_clean['supervisor'].value_counts(normalize=True).round(3) * 100)

"""##### 1. Why did you pick the specific chart?

This count plot shows the comfort level employees have with their direct managers — one of the most critical relationships for workplace mental health support.

##### 2. What is/are the insight(s) found from the chart?

Many employees are willing to talk to at least some of their supervisors, but a noticeable group is not comfortable at all. Manager quality and training clearly make a big difference.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. Investing in manager mental-health literacy training can shift more employees into the “Yes” category. When managers are approachable, employees seek help earlier, reducing escalation of issues and improving retention.

#### Chart - 12: Treatment Rate by Country (Bivariate / Geographic)
"""

# Chart - 12 visualization code
country_treat = pd.crosstab(df_clean['Country_grouped'], df_clean['treatment'], normalize='index') * 100
country_treat = country_treat.sort_values('Yes', ascending=False)

plt.figure(figsize=(11, 6))
country_treat['Yes'].plot(kind='bar', color='teal')
plt.title('Percentage of Respondents Who Sought Treatment by Country', fontsize=14, pad=12)
plt.xlabel('Country')
plt.ylabel('% Who Sought Treatment')
plt.xticks(rotation=30, ha='right')
plt.axhline(y=50, color='red', linestyle='--', alpha=0.7, label='50% Reference Line')
plt.legend()
plt.tight_layout()
plt.show()

print("\nTreatment Percentage by Country:")
print(country_treat.round(1))

"""##### 1. Why did you pick the specific chart?

A bar chart of treatment percentage by geography directly answers one of the key questions in the project brief — how mental health treatment-seeking varies by location.

##### 2. What is/are the insight(s) found from the chart?

Treatment rates vary across countries. The United States shows relatively high treatment-seeking. Some other countries and the “Other” group show different patterns. Note that sample sizes are smaller for some countries, so results should be interpreted with caution.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, especially for global tech companies. Benefits packages, communication style, and cultural messaging may need localization. A single global policy that ignores regional differences may under-serve employees in certain countries.

#### Chart - 13: Ease of Taking Medical Leave for Mental Health (Univariate)
"""

# Chart - 13 visualization code
leave_order = ['Very easy', 'Somewhat easy', "Don't know", 'Somewhat difficult', 'Very difficult']

plt.figure(figsize=(11, 5))
ax = sns.countplot(data=df_clean, x='leave', order=leave_order, palette='RdYlGn')
plt.title('How Easy Is It to Take Medical Leave for a Mental Health Condition?', fontsize=13, pad=12)
plt.xlabel('Ease of Taking Leave')
plt.ylabel('Number of Respondents')
plt.xticks(rotation=20)

for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom', fontsize=10)

plt.tight_layout()
plt.show()

"""##### 1. Why did you pick the specific chart?

An ordered categorical count plot is ideal for showing how easy or difficult employees perceive it is to take mental health leave.

##### 2. What is/are the insight(s) found from the chart?

A large number of employees either find leave difficult or (very commonly) do not know how easy it is. This shows both policy and communication gaps around mental health leave.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. Clear and easy-to-use leave policies reduce presenteeism and burnout. When employees are unsure or find the process difficult, they are more likely to keep working while unwell, which worsens long-term outcomes and productivity.

#### Chart - 14: Correlation Heatmap of Key Variables (Multivariate)
"""

# Chart - 14 - Correlation Heatmap visualization code

# Create a copy and encode key binary variables
df_corr = df_clean.copy()

df_corr['treatment_bin'] = df_corr['treatment'].map({'Yes': 1, 'No': 0})
df_corr['family_history_bin'] = df_corr['family_history'].map({'Yes': 1, 'No': 0})
df_corr['remote_work_bin'] = df_corr['remote_work'].map({'Yes': 1, 'No': 0})
df_corr['tech_company_bin'] = df_corr['tech_company'].map({'Yes': 1, 'No': 0})
df_corr['self_employed_bin'] = df_corr['self_employed'].map({'Yes': 1, 'No': 0})
df_corr['obs_consequence_bin'] = df_corr['obs_consequence'].map({'Yes': 1, 'No': 0})

corr_cols = ['Age', 'treatment_bin', 'family_history_bin', 'remote_work_bin',
             'tech_company_bin', 'self_employed_bin', 'obs_consequence_bin']

corr_matrix = df_corr[corr_cols].corr()

plt.figure(figsize=(9, 7))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', center=0, fmt='.2f', square=True, linewidths=0.5)
plt.title('Correlation Heatmap of Key Numeric / Binary Variables', fontsize=14, pad=12)
plt.tight_layout()
plt.show()

"""##### 1. Why did you pick the specific chart?

A correlation heatmap is the standard way to quickly surface linear relationships among numeric and binary-encoded variables.

##### 2. What is/are the insight(s) found from the chart?

The strongest positive association with treatment is **family_history**. Age and remote work show weaker associations. Having observed negative consequences for coworkers also shows a relationship with treatment-seeking behaviour.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. The heatmap confirms that family history is a key signal. Organizations can use this knowledge (while respecting privacy) to strengthen general awareness campaigns. It also reminds us that cultural factors (observed stigma) matter as much as demographic factors.

#### Chart - 15: Pair Plot of Key Variables (Multivariate)
"""

# Chart - 15 - Pair Plot visualization code
sns.pairplot(df_corr[['Age', 'treatment_bin', 'family_history_bin', 'obs_consequence_bin']],
             hue='treatment_bin', diag_kind='kde', palette='Set1')
plt.suptitle('Pair Plot of Key Variables Colored by Treatment', y=1.02, fontsize=14)
plt.show()

"""##### 1. Why did you pick the specific chart?

A pair plot helps visualize pairwise relationships and distributions at the same time, with points colored by the target variable (treatment). It is useful for spotting patterns that a simple correlation number might miss.

##### 2. What is/are the insight(s) found from the chart?

The pair plot confirms that family history separates the treatment groups more clearly than age. The age distributions of people who sought treatment and those who did not are quite similar.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. It reinforces that demographic variables like age alone are not strong predictors. Cultural and family-history related factors are more important. Programs should focus more on reducing stigma and improving awareness rather than only targeting specific age groups.

#### Chart - 16: Perception of Anonymity Protection (Univariate)
"""

# Chart - 16 visualization code
plt.figure(figsize=(8, 5))
ax = sns.countplot(data=df_clean, x='anonymity',
                   order=['Yes', 'No', "Don't know"], palette='Set2')
plt.title('Is Anonymity Protected if You Use Mental Health Resources?', fontsize=13, pad=12)
plt.xlabel('Anonymity Protected')
plt.ylabel('Number of Respondents')

for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom', fontsize=11)

plt.tight_layout()
plt.show()

print("\nPercentage Distribution:")
print(df_clean['anonymity'].value_counts(normalize=True).round(3) * 100)

"""##### 1. Why did you pick the specific chart?

This count plot highlights a critical trust factor — whether employees believe their anonymity is protected when using mental health resources.

##### 2. What is/are the insight(s) found from the chart?

A very large share of respondents answered “Don’t know”. Even when anonymity is actually protected, many employees are unaware of it. This lack of clarity reduces the likelihood that people will use the available support.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. Clearly and repeatedly communicating confidentiality guarantees can increase benefit utilization at almost zero extra cost. When employees are unsure about anonymity, they often avoid seeking help even if good resources exist.

#### Chart - 17: Does Employer Take Mental Health as Seriously as Physical Health? (Univariate)
"""

# Chart - 17 visualization code
plt.figure(figsize=(8, 5))
ax = sns.countplot(data=df_clean, x='mental_vs_physical',
                   order=['Yes', 'No', "Don't know"], palette='muted')
plt.title('Does Your Employer Take Mental Health as Seriously as Physical Health?', fontsize=13, pad=12)
plt.xlabel('Mental Health Treated Equally')
plt.ylabel('Number of Respondents')

for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom', fontsize=11)

plt.tight_layout()
plt.show()

print("\nPercentage Distribution:")
print(df_clean['mental_vs_physical'].value_counts(normalize=True).round(3) * 100)

"""##### 1. Why did you pick the specific chart?

This chart directly measures the perceived parity between mental health and physical health support in the workplace.

##### 2. What is/are the insight(s) found from the chart?

Many employees either believe that mental health is not treated equally or are unsure. True parity between mental and physical health is still not the lived experience of a large share of the workforce.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. Closing the parity gap (through policy, communication, and leadership behaviour) improves trust and increases the use of mental health resources. When employees feel mental health is taken less seriously, they are less likely to come forward early.

#### Chart - 18: Observed Negative Consequences for Coworkers (Univariate)
"""

# Chart - 18 visualization code
plt.figure(figsize=(7, 5))
ax = sns.countplot(data=df_clean, x='obs_consequence', palette='Reds', order=['No', 'Yes'])
plt.title('Have You Observed Negative Consequences for Coworkers\nwith Mental Health Conditions?', fontsize=13, pad=12)
plt.xlabel('Observed Negative Consequences')
plt.ylabel('Number of Respondents')

for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width()/2., p.get_height()),
                ha='center', va='bottom', fontsize=11)

plt.tight_layout()
plt.show()

print("\nPercentage Distribution:")
print(df_clean['obs_consequence'].value_counts(normalize=True).round(3) * 100)

"""##### 1. Why did you pick the specific chart?

This chart shows how common it is for employees to have witnessed stigma or negative outcomes related to mental health. Such observations strongly influence personal willingness to disclose.

##### 2. What is/are the insight(s) found from the chart?

A meaningful minority of respondents have observed negative consequences for coworkers. Even if the majority have not personally seen it, the existence of such stories spreads fear and discourages openness.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. Organizations should investigate and address any real negative consequences (or the perception of them). Sharing visible positive stories of support and recovery can counteract the chilling effect created by observed stigma.

#### Chart - 19: Treatment Seeking by Age Group (Bivariate)
"""

# Chart - 19 visualization code
plt.figure(figsize=(10, 5))
ax = sns.countplot(data=df_clean, x='Age_group', hue='treatment', palette='Set1')
plt.title('Treatment Seeking Behaviour by Age Group', fontsize=14, pad=12)
plt.xlabel('Age Group')
plt.ylabel('Number of Respondents')
plt.legend(title='Sought Treatment')

plt.tight_layout()
plt.show()

print("\nPercentage who sought treatment by Age Group:")
ct = pd.crosstab(df_clean['Age_group'], df_clean['treatment'], normalize='index') * 100
print(ct.round(1))

"""##### 1. Why did you pick the specific chart?

This grouped bar chart examines whether treatment-seeking behaviour differs across different career stages / age bands.

##### 2. What is/are the insight(s) found from the chart?

Treatment rates are fairly consistent across age groups, with some variation. The 26-35 age group is the largest and shows substantial treatment-seeking. Age alone is not a dramatic differentiator.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes. Support programs should be available across the entire career span. Focusing only on early-career or only on senior employees would leave important gaps. A broad, inclusive approach is more effective.

#### Chart - 20: Awareness of Care Options vs Treatment Seeking (Bivariate)
"""

# Chart - 20 visualization code
plt.figure(figsize=(9, 5))
ax = sns.countplot(data=df_clean, x='care_options', hue='treatment',
                   order=['Yes', 'No', 'Not sure'], palette='Set2')
plt.title('Awareness of Employer Care Options vs Seeking Treatment', fontsize=13, pad=12)
plt.xlabel('Knows About Care Options')
plt.ylabel('Number of Respondents')
plt.legend(title='Sought Treatment')

plt.tight_layout()
plt.show()

print("\nPercentage who sought treatment by Care Options Awareness:")
ct = pd.crosstab(df_clean['care_options'], df_clean['treatment'], normalize='index') * 100
print(ct.round(1))

"""##### 1. Why did you pick the specific chart?

This chart tests the important hypothesis that awareness of available care options is linked to higher rates of treatment-seeking.

##### 2. What is/are the insight(s) found from the chart?

Respondents who know their employer’s care options have markedly higher treatment rates than those who do not know or are unsure. Awareness is strongly associated with taking action.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes — this is one of the highest-ROI findings. Improving awareness of existing care options through repeated, multi-channel communication can increase help-seeking without requiring significant new benefit spend. Low awareness means companies are under-utilizing the support they already pay for.

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective?
Explain Briefly.

Based on the complete Exploratory Data Analysis of the 2014 OSMI Mental Health in Tech Survey, the following practical and high-impact recommendations are suggested for technology organizations:

**1. Close the Awareness Gap (Highest ROI action)**
- A large percentage of employees answered “Don’t know” for benefits, care options, anonymity protection, and leave policies.
- **Action**: Improve communication through multiple channels — onboarding sessions, intranet, manager toolkits, email campaigns, and regular reminders.
- This can significantly increase utilization of existing benefits without major additional cost.

**2. Reduce Fear of Negative Consequences**
- Many employees still fear that discussing mental health with their employer could harm their career.
- **Action**:
  - Visible leadership commitment and open conversations from senior leaders.
  - Mandatory manager training on mental health conversations.
  - Clear non-retaliation policies.
  - Sharing positive stories of employees who received support.

**3. Make Mental Health Leave Clear and Easy**
- A high number of respondents either find leave difficult or do not know the process.
- **Action**: Simplify the leave application process and clearly publish how employees can take time off for mental health reasons.

**4. Treat Mental Health with the Same Seriousness as Physical Health**
- Many employees feel that mental health is not treated equally.
- **Action**: Align policies, benefits, and managerial responses so that mental health is given equal importance in practice, not just in statements.

**5. Use Strong Predictors to Guide Support**
- Family history is one of the strongest predictors of treatment-seeking.
- Gender differences exist (females show higher treatment rates).
- **Action**: Design inclusive awareness campaigns. Pay special attention to reducing stigma among male employees who may be less likely to seek help.

**6. Localize Support for Global Teams**
- Treatment rates and attitudes vary by country.
- **Action**: Avoid a rigid one-size-fits-all global policy. Adapt communication and benefits slightly according to regional needs and cultural context.

**7. Strengthen Manager Capability**
- Willingness to talk to supervisors varies widely.
- **Action**: Train managers to respond supportively and confidentially when employees raise mental health concerns.

---

**Expected Business Impact:**
- Higher utilization of existing mental health benefits
- Earlier help-seeking and reduced severity of issues
- Lower presenteeism and burnout
- Improved employee trust, engagement, and retention
- Stronger employer brand as a mentally healthy workplace

# **Conclusion**

The 2014 OSMI Mental Health in Tech Survey clearly shows that mental health concerns are widespread in the technology sector. Nearly half of the respondents have sought treatment for a mental health condition, confirming that this is not a marginal issue.

Key findings from the analysis include:

- Family history of mental illness is a strong predictor of treatment-seeking behaviour.
- A large portion of employees remain unaware of the mental health benefits, care options, and anonymity protections offered by their employers.
- Fear of negative career consequences still acts as a major barrier to openness.
- Many employees do not feel that mental health is treated with the same seriousness as physical health.
- Work interference due to mental health is common among those who experience it.
- Geographic and gender differences exist and should be considered while designing programs.

By focusing on better communication, manager training, clear leave policies, and creating a culture of psychological safety, technology companies can convert existing benefits into real support. These steps will help reduce stigma, increase help-seeking, protect productivity, and build a healthier and more sustainable workforce.

This EDA followed a complete and structured approach — data understanding, thorough cleaning (especially Age and Gender), univariate, bivariate and multivariate analysis with 20 meaningful charts, and clear, actionable business recommendations aligned with the original problem questions.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""